#version 450

#extension GL_EXT_control_flow_attributes : enable
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int32 : require
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_shader_subgroup_ballot : enable

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout (binding = 0) readonly buffer M   { float16_t data_m[]; };
layout (binding = 1) writeonly buffer SM { int data_sm[]; };

#include "flash_attn_sparse_compact.glsl"

layout(push_constant) uniform parameter {
    CompactionParams p;
};

void main() {
    run_sparse_compact(gl_WorkGroupID.x, gl_WorkGroupID.y, gl_WorkGroupID.z, p);
}
