// Thinking-wire parser/serializer/grammar tests. Pure string logic, no llama deps.
//
// The wire is what the server holds in probe_bytes: the injected prefix
// (`<ul>Let me see what can be thought through on its own here...<li>`), then the
// generated bytes -- punctuation-free `<li>` aspects -- closed by `</ul>`.
// Everything is fail-closed: an illegal envelope, an empty aspect, free text
// between items, or a stream that ends before the terminator must be an error,
// never a silently repaired plan.

#include "server-rerot-thinking.h"

#include <cstdio>
#include <string>

static int failures = 0;

#define CHECK(expr)                                                              \
    do {                                                                         \
        if (!(expr)) {                                                            \
            ++failures;                                                           \
            std::printf("FAIL %s:%d: %s\n", __FILE__, __LINE__, #expr);           \
        }                                                                         \
    } while (0)

// Generation continues inside the first item, so `generated` starts with its text.
static std::string wire(const std::string & generated) {
    return std::string(server_thinking::probe_prefix) + generated;
}

int main() {
    using namespace server_thinking;

    // Envelope contract: the prompt ends on a newline (the injection path hard
    // aborts otherwise); the prefix opens the list and the first item, with no free
    // head region left between them.
    CHECK(!prompt.empty() && prompt.back() == '\n');
    CHECK(probe_prefix.rfind(open_list, 0) == 0);
    CHECK(open_item == "<li>");                      // no class attribute to drop
    CHECK(probe_prefix.size() > open_list.size() + open_item.size());  // starter text
    CHECK(probe_prefix.substr(probe_prefix.size() - open_item.size()) == open_item);

    // Streaming: no terminator yet -> incomplete, no error, nothing accepted.
    {
        const auto r = parse(wire("slot occupancy"));
        CHECK(!r.complete);
        CHECK(r.error.empty());
        CHECK(r.items.empty());
    }

    // Several aspects; the starter text between <ul> and the first <li> is dropped.
    {
        const auto r = parse(wire(
            "which slot fields exist today</li>\n"
            "<li>where the endpoint gets registered</li>\n"
            "<li>risks of reading slot state concurrently</li>\n"
            "</ul>"));
        CHECK(r.complete);
        CHECK(r.error.empty());
        CHECK(r.items.size() == 3);
        CHECK(r.items.size() == 3 && r.items[0] == "which slot fields exist today");
        CHECK(r.items.size() == 3 && r.items[1] == "where the endpoint gets registered");
        CHECK(r.items.size() == 3 && r.items[2] == "risks of reading slot state concurrently");
    }

    // A single aspect, and an optional space after <li> is accepted/trimmed.
    {
        const auto r = parse(wire(" which file owns the retry budget</li></ul>"));
        CHECK(r.complete);
        CHECK(r.items.size() == 1 && r.items[0] == "which file owns the retry budget");
    }

    // An aspect may be long, multilingual, and carry path characters and commas.
    // It may not contain '<', which is why the first </ul> is always the terminator.
    {
        const std::string long_a =
            "tools/server/server-rerot-thinking cpp 里探针如何把计划交给 worker, "
            "谁负责冻结计划, 谁负责丢弃探针 KV, 失败时是不是 fail closed";
        const auto r = parse(wire(long_a + "</li></ul>"));
        CHECK(r.complete);
        CHECK(r.items.size() == 1 && r.items[0] == long_a);
        CHECK(r.items.size() == 1 && r.items[0].size() > 120);
    }

    // Text after the terminator is discarded, not parsed.
    {
        const auto r = parse(wire("first aspect</li></ul>\nNow the copies take over."));
        CHECK(r.complete);
        CHECK(r.items.size() == 1 && r.items[0] == "first aspect");
    }

    // Fail closed: the list closed without a single aspect. The grammar must also
    // make this unreachable (</ul> only after one complete item).
    {
        const auto bare = parse(std::string(open_list) + "</ul>");
        CHECK(!bare.complete);
        CHECK(!bare.error.empty());
        const auto starter_only = parse(std::string(open_list) + "let me look</ul>");
        CHECK(!starter_only.complete);
        CHECK(!starter_only.error.empty());
    }

    // Fail closed: free text between items (the "think between" failure mode).
    {
        const auto r = parse(wire("first</li>hmm wait let me reconsider<li>second</li></ul>"));
        CHECK(!r.complete);
        CHECK(!r.error.empty());
    }

    // Fail closed: empty and whitespace-only aspects.
    {
        const auto empty_item = parse(wire("</li></ul>"));
        CHECK(!empty_item.complete);
        CHECK(!empty_item.error.empty());
        const auto blank_item = parse(wire("   </li></ul>"));
        CHECK(!blank_item.complete);
        CHECK(!blank_item.error.empty());
    }

    // Fail closed: an item that is never closed although the list closed.
    {
        const auto r = parse(wire("dangling aspect</ul>"));
        CHECK(!r.complete);
        CHECK(!r.error.empty());
    }

    // Fail closed: markup inside an aspect, and a foreign tag where an item must
    // start.
    {
        const auto nested = parse(wire("first <b>bold</b></li></ul>"));
        CHECK(!nested.complete);
        CHECK(!nested.error.empty());
        const auto foreign = parse(wire("first</li><p>second</p></ul>"));
        CHECK(!foreign.complete);
        CHECK(!foreign.error.empty());
    }

    // Fail closed: wrong envelope, and a source that stopped before </ul>.
    {
        const auto bad_open = parse("<ol>starter<li>first</li></ul>");
        CHECK(!bad_open.complete);
        CHECK(!bad_open.error.empty());
        const auto eog = parse(wire("first</li>"), /*eof =*/true);
        CHECK(!eog.complete);
        CHECK(!eog.error.empty());
        const auto streaming = parse(wire("first</li>"), /*eof =*/false);
        CHECK(!streaming.complete);
        CHECK(streaming.error.empty());
    }

    // stop_offset: npos until the terminator, then its exact offset, including when
    // the tag is split across token pieces (incremental begin overlap).
    {
        const std::string partial = wire("first</li></u");
        CHECK(stop_offset(partial) == std::string_view::npos);
        const std::string full = partial + "l>";
        const size_t expected = full.find("</ul>");
        CHECK(stop_offset(full) == expected);
        CHECK(stop_offset(full, partial.size()) == expected);
    }

    // Round trip: the canonical render carries no starter text and parses back to
    // the same aspects.
    {
        const std::vector<std::string> items = {
            "where the retry budget is enforced today",
            "哪些测试会因为这次改动失败",
        };
        const std::string canonical = serialize(items);
        CHECK(canonical.rfind(std::string(open_list) + "\n", 0) == 0);
        CHECK(canonical.find(std::string(terminator) + "\n") != std::string::npos);
        CHECK(canonical.find("Let me see") == std::string::npos);
        const auto r = parse(canonical);
        CHECK(r.complete);
        CHECK(r.items == items);
    }

    // Grammar text: the rules the sampler needs, and none of the concepts that
    // failed (no indentation, no head region, no class attribute).
    {
        const std::string g = grammar();
        CHECK(g.rfind("root ::= sp? text", 0) == 0);   // starts inside the first item
        CHECK(g.find("head ::=") == std::string::npos);
        CHECK(g.find("indent") == std::string::npos);
        CHECK(g.find("class") == std::string::npos);
        CHECK(g.find("\"</li>\"") != std::string::npos);
        CHECK(g.find("\"</ul>\"") != std::string::npos);
        // One breath: words, spaces and commas only. No sentence punctuation means
        // an aspect cannot hold prose, which is what lets '</li>' stay reachable.
        CHECK(g.find("tchar ::= wchar | sp | comma") != std::string::npos);
        CHECK(g.find("text ::= wchar tchar*") != std::string::npos);
        CHECK(g.find("wchar ::= [0-9A-Za-z/_") != std::string::npos);
        // </ul> sits after an item, never as an alternative to the first one.
        const std::string root = g.substr(0, g.find('\n'));
        CHECK(root.find("text") < root.find("</ul>"));
    }

    if (failures == 0) {
        std::printf("PASS: test-rerot-thinking\n");
        return 0;
    }
    std::printf("FAIL: test-rerot-thinking (%d)\n", failures);
    return 1;
}
