#include "repetition-corpus.h"

#include <algorithm>
#include <cstddef>
#include <cctype>
#include <cstdint>
#include <string>
#include <unordered_set>

namespace {

const std::unordered_set<std::string> source_document_extensions = {
    ".c", ".cc", ".cpp", ".cxx", ".h", ".hh", ".hpp", ".hxx",
    ".cu", ".cuh", ".cl", ".comp", ".glsl", ".wgsl", ".metal",
    ".cs", ".fs", ".fsi", ".fsx", ".fsproj", ".java", ".kt", ".kts", ".swift",
    ".go", ".rs", ".py", ".pyi", ".rb", ".php", ".lua", ".pl",
    ".js", ".mjs", ".cjs", ".jsx", ".ts", ".tsx", ".svelte",
    ".css", ".scss", ".sh", ".bash", ".zsh", ".fish", ".ps1", ".bat",
    ".cmake", ".mk", ".nix", ".gradle", ".props", ".pro", ".ld", ".idl",
    ".jinja", ".gbnf", ".tmpl", ".template", ".schema", ".in",
    ".toml", ".yaml", ".yml", ".md", ".mdx", ".rst", ".adoc",
};

const std::unordered_set<std::string> source_document_names = {
    "APPLIES-TO", "AUTHORS", "CMakeLists.txt", "CODEOWNERS", "Dockerfile", "LICENSE", "Makefile",
};

const std::unordered_set<std::string> excluded_segments = {
    "build", "deps", "dist", "fixture", "fixtures", "generated", "node_modules",
    "golden", "goldens", "snapshot", "snapshots", "testdata",
    "third-party", "third_party", "vendor", "vendors",
};

std::string lower(std::string value) {
    std::transform(value.begin(), value.end(), value.begin(), [](unsigned char c) {
        return static_cast<char>(std::tolower(c));
    });
    return value;
}

bool valid_utf8(const std::string & text) {
    const auto * p = reinterpret_cast<const unsigned char *>(text.data());
    std::size_t i = 0;

    while (i < text.size()) {
        const unsigned char c = p[i++];
        if (c <= 0x7f) {
            continue;
        }

        int n = 0;
        uint32_t cp = 0;
        if (c >= 0xc2 && c <= 0xdf) {
            n = 1;
            cp = c & 0x1f;
        } else if (c >= 0xe0 && c <= 0xef) {
            n = 2;
            cp = c & 0x0f;
        } else if (c >= 0xf0 && c <= 0xf4) {
            n = 3;
            cp = c & 0x07;
        } else {
            return false;
        }

        if (i + n > text.size()) {
            return false;
        }

        for (int j = 0; j < n; ++j) {
            const unsigned char cc = p[i++];
            if ((cc & 0xc0) != 0x80) {
                return false;
            }
            cp = (cp << 6) | (cc & 0x3f);
        }

        if ((n == 2 && cp < 0x800) || (n == 3 && cp < 0x10000) ||
                (cp >= 0xd800 && cp <= 0xdfff) || cp > 0x10ffff) {
            return false;
        }
    }

    return true;
}

} // namespace

bool wanxiangqi_repetition_corpus_path(const std::filesystem::path & path) {
    for (const auto & part : path.parent_path()) {
        if (excluded_segments.count(lower(part.string())) != 0) {
            return false;
        }
    }

    const std::string name = path.filename().string();
    if (source_document_names.count(name) != 0 || name.rfind("Dockerfile.", 0) == 0) {
        return true;
    }

    return source_document_extensions.count(lower(path.extension().string())) != 0;
}

bool wanxiangqi_repetition_corpus_text(const std::string & text) {
    if (!valid_utf8(text)) {
        return false;
    }

    const std::string prefix = lower(text.substr(0, 4096));
    return prefix.find("auto-generated") == std::string::npos &&
           prefix.find("autogenerated") == std::string::npos &&
           prefix.find("do not edit") == std::string::npos &&
           prefix.find("generated with") == std::string::npos &&
           prefix.find("pre-computed rotation matrices") == std::string::npos;
}
