#pragma once

#include "llama.h"

#include <array>
#include <cstddef>
#include <cstdint>
#include <limits>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <vector>

// Internal, experimental support for Recursive Elastic Ring-of-Thought (RERoT).
//
// This header deliberately contains only stable logical identifiers and pure
// view/DDVR helpers. Physical KV ownership remains in llama_kv_cells and server
// scheduling remains in tools/server/server-rerot.*.

using llama_rerot_node_id = uint32_t;
using llama_rerot_run_id  = uint32_t;

static constexpr llama_rerot_node_id LLAMA_REROT_NODE_INVALID =
    std::numeric_limits<llama_rerot_node_id>::max();
static constexpr llama_rerot_run_id LLAMA_REROT_RUN_INVALID =
    std::numeric_limits<llama_rerot_run_id>::max();

enum class llama_rerot_visibility : uint8_t {
    normal = 0,
    public_live,
    private_control,
    pending_record,
};

// Segment kind for presentation vs model-internal protocol (AGENTS.md §§04, 07).
// - frame: runtime-injected subagent fixed entry (close previous + tool handoff + open reasoning)
// - body: worker/synthesis reasoning body
// - source_end: native </think> or terminal event token (kept in source tape, not exported to foreign views)
// - probe_control: planning schema probe control text
enum class llama_rerot_segment_kind : uint8_t {
    body = 0,
    frame,
    source_end,
    probe_control,
};

// Provenance for reasoning termination events (§04.6)
enum class llama_rerot_event_origin : uint8_t {
    unknown = 0,
    runtime_frame,       // Injected in F_i, cannot complete a task
    foreign_export,      // From peer export, cannot complete current task
    worker_source,       // Generated by current worker's sampling stream
    synthesis_source,    // Generated by 0.synthesize sampling stream
    forced_abort,        // Cancel / resource exhaustion / error
};

// 0.plan and 0.synthesize share actor label 0 but must not share this identity.
enum class llama_rerot_stage_role : uint8_t {
    planner = 0,
    worker,
    synthesis,
};

// Metadata attached to the physical KV cell by llama_kv_cells. Keeping this
// POD-like and index-local lets existing save/copy/pack code move it together
// with position, extents, shifts, and sequence references.
struct llama_kv_rerot_meta {
    uint64_t episode_id = 0;
    llama_rerot_node_id node_id = LLAMA_REROT_NODE_INVALID;
    llama_rerot_run_id run_id = LLAMA_REROT_RUN_INVALID;
    uint64_t publish_epoch = 0;
    uint64_t frontier = 0;
    llama_rerot_visibility visibility = llama_rerot_visibility::normal;

    void reset() {
        episode_id = 0;
        node_id = LLAMA_REROT_NODE_INVALID;
        run_id = LLAMA_REROT_RUN_INVALID;
        publish_epoch = 0;
        frontier = 0;
        visibility = llama_rerot_visibility::normal;
    }

    bool active() const {
        return episode_id != 0;
    }

    bool operator==(const llama_kv_rerot_meta & other) const {
        return episode_id == other.episode_id &&
               node_id == other.node_id &&
               run_id == other.run_id &&
               publish_epoch == other.publish_epoch &&
               frontier == other.frontier &&
               visibility == other.visibility;
    }

    bool operator!=(const llama_kv_rerot_meta & other) const {
        return !(*this == other);
    }
};

enum class llama_rerot_node_state : uint8_t {
    planning = 0,
    terminal_running,
    forked,
    queued,
    starting,
    running,
    retired,
    ready_suspended,
};

struct llama_rerot_run {
    llama_rerot_run_id id = LLAMA_REROT_RUN_INVALID;
    llama_rerot_node_id owner = LLAMA_REROT_NODE_INVALID;
    llama_rerot_visibility visibility = llama_rerot_visibility::normal;
    llama_rerot_segment_kind kind = llama_rerot_segment_kind::body;

    llama_pos storage_pos0 = 0;
    uint32_t token_count = 0;

    // Publication-epoch contract (enforced by append_run and validate,
    // mirroring the KV cell rules): public_live requires a non-zero publish
    // epoch, while normal, private_control, and pending_record require zero.
    // A pending run becomes public only through publish_run/reclassify_run,
    // which assign the epoch atomically with the visibility change.
    uint64_t publish_epoch = 0;
};

struct llama_rerot_node {
    llama_rerot_node_id id = LLAMA_REROT_NODE_INVALID;
    llama_rerot_node_id parent = LLAMA_REROT_NODE_INVALID;

    uint32_t depth = 0;
    uint32_t child_index = 0;
    std::string title;

    llama_rerot_node_state state = llama_rerot_node_state::planning;

    // Both vectors preserve semantic/document order.
    std::vector<llama_rerot_node_id> children;
    std::vector<llama_rerot_run_id> runs;

    // DAG topological extensions (AGENTS.md §§01, 03, 07):
    // Predecessors are hard start dependencies (u -> v).
    // Successors are outgoing edges (v -> w).
    // plan_rank is the index in the original planning list/questions array.
    uint32_t plan_rank = 0;
    llama_rerot_stage_role stage_role = llama_rerot_stage_role::planner;
    std::vector<llama_rerot_node_id> predecessors;
    std::vector<llama_rerot_node_id> successors;
};

struct llama_rerot_view_run {
    // Logical span triple (run_id, virtual_pos0, token_count) flattened from
    // one PAC-DFS reader view. This struct is the only view-to-layout input
    // and MUST never carry physical KV indices (cell/key/seq ids): the KV
    // cache resolves run_ids to resident cells itself, so TriAttention
    // compaction never invalidates a previously built view. The remaining
    // fields mirror the source run for span flattening without consulting
    // physical state.
    llama_rerot_run_id run_id = LLAMA_REROT_RUN_INVALID;
    llama_rerot_node_id owner = LLAMA_REROT_NODE_INVALID;

    llama_pos storage_pos0 = 0;
    llama_pos virtual_pos0 = 0;
    uint32_t token_count = 0;
    uint64_t publish_epoch = 0;
};

struct llama_rerot_reader_view {
    uint64_t episode_id = 0;
    llama_rerot_node_id reader = LLAMA_REROT_NODE_INVALID;
    std::vector<llama_rerot_view_run> runs;
    llama_pos query_virtual_pos = 0;
};

// A reader view installed on an execution sequence. The logical document is
// owned by the scheduler; the KV cache only needs the stable ordered run ids
// and enough clock information to decide staged frontier visibility.
struct llama_rerot_reader_state {
    uint64_t episode_id = 0;
    llama_rerot_node_id reader = LLAMA_REROT_NODE_INVALID;
    llama_rerot_run_id query_run = LLAMA_REROT_RUN_INVALID;
    uint64_t frontier = 0;

    uint64_t topology_epoch = 0;
    uint64_t publish_epoch = 0;
    uint64_t layout_epoch = 0;

    llama_rerot_frontier_mode frontier_mode = LLAMA_REROT_FRONTIER_STRONG;
    std::vector<llama_rerot_run_id> ordered_runs;
    llama_seq_id seq_id = -1;

    void reset() {
        episode_id = 0;
        reader = LLAMA_REROT_NODE_INVALID;
        query_run = LLAMA_REROT_RUN_INVALID;
        frontier = 0;
        topology_epoch = 0;
        publish_epoch = 0;
        layout_epoch = 0;
        frontier_mode = LLAMA_REROT_FRONTIER_STRONG;
        ordered_runs.clear();
        seq_id = -1;
    }

    bool active() const {
        return episode_id != 0;
    }
};

// Backend-neutral indexed attention layout. Each group is one copy of an
// original query evaluated at an effective RoPE position. Entries select a
// physical K/V row and the query group to use for that row. Query offsets make
// all entries for one output query contiguous, allowing one global online
// softmax per query/head without materializing or rephasing K.
struct llama_rerot_attn_group {
    uint32_t query_index = 0;
    llama_pos effective_pos = 0;
};

struct llama_rerot_attn_entry {
    uint32_t key_index = 0;
    uint32_t group_index = 0;
};

struct llama_rerot_attn_layout {
    uint32_t n_queries = 0;
    std::vector<llama_rerot_attn_group> groups;
    std::vector<llama_rerot_attn_entry> entries;
    std::vector<uint32_t> query_offsets;
    // Contiguous span description of the same entry stream (sixteenth
    // round: question two of the compute-organization review). Each span
    // fills entries[query_offsets[i] + inner .. + count) with the ascending
    // key range [key_start, key_start + count), all tagged group_index.
    // Emitted by the sink during the merge for every bulk
    // (const-effective, contiguous-identity) segment — 12 appends per
    // query instead of ~K per-entry struct writes. The loader
    // (fill_spans) expands the span table into the i32 entry tensor.
    //
    // A segment that is NOT expressible (non-monotone keys, scalar merge
    // arms) is simply absent from the table: the entry vector stays
    // authoritative, so general shapes pay nothing and keep working.
    struct span {
        uint32_t key_start   = 0;   // first physical key of the range
        uint32_t count       = 0;   // range length (keys are +1 ascending)
        uint32_t group_index = 0;   // entry group for the whole range
        uint32_t entry_index = 0;   // GLOBAL entry slot of key_start
        // Absorption note (sixteenth round): a span is emitted DURING the
        // merge, before the enclosing group index exists; the group is
        // stamped after (see multi_reader_numeric_pass). entry_index lets
        // the loader expand O(spans) without scanning.
    };
    std::vector<span> spans;

    // R13-A compact span ABI (C05):
    //  - Spans are a compressed description of a suffix of the authoritative
    //    entry stream; the entries vector stays authoritative for every row
    //    a span does NOT cover (dense compatibility).
    //  - On the wire/GPU side a span is 16 bytes: {u32 key_start, u32 count,
    //    u32 group_index, u32 entry_index}; LLAMA_REROT_SPAN_ABI_VERSION
    //    identifies this layout. A consumer that does not understand the
    //    version MUST treat the spans table as absent (dense entries only).
    //  - Invariants enforced by validate():
    //      sp.count > 0
    //      sp.entry_index + sp.count <= n_entries (no overflow)
    //      entry_index non-decreasing across spans; span-covered key ranges
    //        are +1 ascending and share one group_index
    //  - Coverage accounting: span_rows(spans) + spill_rows(entries not
    //    covered) == n_entries.

    bool empty() const {
        return n_queries == 0;
    }

    // Reset for a fresh build while RETAINING capacity AND the entries'
    // exact size: the builder pre-sizes `entries` to the frontier's upper
    // bound by cursor write, so keeping the size makes the steady-state
    // resize a no-op (no value-init pass over ~25MB). `groups` are
    // appended by the sink (push_back) and must start empty; offsets are
    // rebuilt by push_back. Stale bytes in `entries` beyond the emitted
    // cursor are never read: the shrink at the end caps the size.
    void clear() {
        n_queries = 0;
        groups.clear();
        spans.clear();
        query_offsets.clear();
    }

    bool validate(uint32_t n_keys, std::string * error = nullptr) const;


    // Persistent duplicate-key scratch for the validating mode: the layout
    // object lives across frontiers inside the KV cache, so the bitmap is
    // allocated once and only touched bytes are walked per query (the
    // validating walk itself clears what it sets — the scratch is all-zero
    // between validate() calls by construction).
    // Not serialized, not part of layout identity; mutable because
    // validate() is const.
    mutable std::vector<uint8_t> validate_scratch_storage;
};

// Minimal physical-key description used by the pure layout builder. The KV
// cache fills `owned_by_reader` from sequence references; no physical-cell
// registry is retained by the logical scheduler.
struct llama_rerot_key_record {
    uint32_t key_index = 0;
    llama_pos storage_pos = 0;
    bool owned_by_reader = false;
    llama_kv_rerot_meta meta;
};

struct llama_rerot_query_layout {
    std::vector<llama_rerot_attn_group> groups;
    std::vector<llama_rerot_attn_entry> entries;
    llama_pos query_virtual_pos = 0;
};

// Build the layout for one query token. Untagged keys form the common/serial
// prefix; tagged keys are ordered by `reader.ordered_runs`. The returned query
// groups are local to this query and are remapped when multiple query layouts
// are combined by the KV cache.
llama_rerot_query_layout llama_rerot_build_query_layout(
    const llama_rerot_reader_state & reader,
    llama_pos query_storage_pos,
    const std::vector<llama_rerot_key_record> & keys);

// Snapshot representation of an active cell in a run bucket.
struct llama_rerot_snapshot_cell {
    uint32_t key_index = 0;
    llama_pos storage_pos = 0;
    uint64_t frontier = 0;
    llama_rerot_node_id node_id = LLAMA_REROT_NODE_INVALID;
    llama_rerot_visibility visibility = llama_rerot_visibility::normal;
    uint64_t seq_mask = 0; // bitmask of batch-local sequence ownership
};

// Snapshot representation of an untagged prefix/base cell.
struct llama_rerot_snapshot_base_cell {
    uint32_t key_index = 0;
    llama_pos storage_pos = 0;
    uint64_t seq_mask = 0; // bitmask of batch-local sequence ownership
};

// Read-only KV snapshot capturing cell metadata, prefix slices, and run indexes
// for all queries within a single batch. Strictly stack-local; discarded after
// batch attention layout construction.
struct llama_rerot_kv_snapshot {
    uint64_t episode_id = 0;

    // Ordered prefix cells, pre-sorted by (storage_pos, key_index).
    std::vector<llama_rerot_snapshot_base_cell> base_cells;

    // Active tagged cells grouped by run_id. Each bucket is pre-sorted
    // by (storage_pos, frontier, key_index).
    std::unordered_map<llama_rerot_run_id, std::vector<llama_rerot_snapshot_cell>> run_buckets;

    // Sequence index mapping for batch-local seq_ids (up to 64 sequences per ubatch).
    std::unordered_map<llama_seq_id, uint32_t> seq_to_index;

    // Reader node to sequence index mapping (for multi-lane/agent scenarios or tests).
    std::unordered_map<llama_rerot_node_id, uint32_t> node_to_index;

    // Diagnostic/verification counters (used by differential tests to prove sharing).
    mutable size_t query_eval_count = 0;
    mutable size_t bucket_lookup_count = 0;

    bool is_owned(uint64_t mask, const llama_rerot_reader_state & reader) const {
        if (mask == 0) {
            return false;
        }
        if (seq_to_index.empty() && node_to_index.empty()) {
            return (mask & 1ULL) != 0;
        }
        if (reader.seq_id >= 0) {
            const auto it = seq_to_index.find(reader.seq_id);
            if (it != seq_to_index.end()) {
                return (mask & (1ULL << it->second)) != 0;
            }
        }
        if (reader.reader != LLAMA_REROT_NODE_INVALID) {
            const auto it = node_to_index.find(reader.reader);
            if (it != node_to_index.end()) {
                return (mask & (1ULL << it->second)) != 0;
            }
        }
        if (seq_to_index.size() == 1) {
            return (mask & 1ULL) != 0;
        }
        return false;
    }

    // Factory method for testing: capture from key records (single reader).
    static llama_rerot_kv_snapshot from_keys(
        const std::vector<llama_rerot_key_record> & keys,
        uint64_t episode_id = 0);

    // Factory method for testing: capture from key records with multiple reader sequences.
    static llama_rerot_kv_snapshot from_multi_reader_keys(
        const std::vector<llama_rerot_key_record> & keys,
        const std::vector<llama_rerot_reader_state> & readers,
        const std::vector<std::vector<bool>> & reader_key_ownership);
};

// Fast shared-snapshot overload: builds layout for one query from the pre-indexed
// run buckets and sorted base slices captured for the current batch.
llama_rerot_query_layout llama_rerot_build_query_layout(
    const llama_rerot_reader_state & reader,
    llama_pos query_storage_pos,
    const llama_rerot_kv_snapshot & snapshot);
// Batched counterpart for query rows sharing ONE reader state (2026-09-22
// compute-organization round: structure/numeric separation in the decode hot
// path). The structural pass — visibility classification (FULL vs
// causally-gated), per-arm ordering, per-key prefix counts, own-row lookup
// table — runs ONCE per call, and every query row then performs only numeric
// work: causal cuts by binary search over precomputed storage arrays,
// virtual arithmetic from prefix counts, effective-position grouping by one
// stable sort of the visible entries. Output[i] is EXACTLY
// llama_rerot_build_query_layout(reader, query_storage_pos[i], keys) — same
// groups, same entries, same order, same query_virtual_pos — so the per-query
// builder remains the oracle (tests compare the two directly). Ownership in
// `keys` must already reflect ONE sequence (rows sharing a reader-view slot
// share their execution sequence); the caller fills it per group.
// Throws the same exceptions as the per-query builder, in the same order
// (reader validity, every position, run view, then per-key checks).
std::vector<llama_rerot_query_layout> llama_rerot_build_query_layouts_shared(
    const llama_rerot_reader_state & reader,
    const std::vector<llama_pos> & query_storage_pos,
    const std::vector<llama_rerot_key_record> & keys);

// Multi-reader counterpart (2026-09-22 fifth round, Q3 host-side deepening).
// R pens of one frontier share ONE key world: the structural pass — episode
// filter, run classification, per-run ascending storage arrays, deviation
// (s - i) ordering — is computed ONCE over `keys` and served to every
// reader; each reader then pays only its ownership-dependent work (own-run
// gate, base-arm membership) plus its per-query numeric pass.
// `keys` must be ONE shared table whose owned_by_reader column is IGNORED
// (ownership is per (reader, run) and derived from meta.run_id ==
// reader.query_run inside); readers must share one episode. Output[r][i] is
// EXACTLY llama_rerot_build_query_layout(readers[r], query_pos[r][i],
// keys-with-r's-ownership-column) — same groups, entries, order and
// query_virtual_pos as the per-group shared builder. Throws the same
// exceptions as the per-query builder (reader validity, positions, run
// view, duplicate keys, negative storage).
std::vector<std::vector<llama_rerot_query_layout>> llama_rerot_build_query_layouts_multi_reader(
    const std::vector<llama_rerot_reader_state> & readers,
    const std::vector<std::vector<llama_pos>> & query_storage_pos,
    const std::vector<llama_rerot_key_record> & keys,
    const std::vector<std::vector<uint8_t>> & base_owned);

// Packed ownership columns (2026-09-22 tenth round, Q3 host-side tail).
// The cache level already builds per-reader ownership as bitsets over the
// shared key table; the byte-vector overload above forced an R x K expansion
// that the builder then re-read row by row. A bitset view carries no
// llama-kv-cells dependency — it is a plain pointer + width — so the pure
// builder stays type-independent while consuming packed bits directly.
struct llama_rerot_owned_view {
    // bits[i] bit (i & 63): reader owns shared-table row i. Null words read
    // as zero (unowned).
    const uint64_t * bits = nullptr;
    size_t n_words = 0;
};

// Bitset-consuming core. Identical output to the byte-vector overload
// (same groups, entries, order, query_virtual_pos; same exceptions).
std::vector<std::vector<llama_rerot_query_layout>> llama_rerot_build_query_layouts_multi_reader_bits(
    const std::vector<llama_rerot_reader_state> & readers,
    const std::vector<std::vector<llama_pos>> & query_storage_pos,
    const std::vector<llama_rerot_key_record> & keys,
    const std::vector<llama_rerot_owned_view> & base_owned_bits);

// Persistent shared world (2026-09-22 eleventh round, fourth question:
// "compile the DAG into a structural program; most frontiers only update
// numbers"). The structural pass of the multi-reader builder — run
// bucketing by (episode, run, node), per-run tagged ordering, deviation
// tables, uniformity probes, fast-key columns, untagged ordering — is a
// function of the KEY TABLE only. On the production shape the table is
// append-only between structural events (a new token appends its cell's
// record; publish reclassifies meta in place without changing order), so
// the structural pass can be computed once per structural event and
// REUSED by every subsequent frontier, leaving each frontier only the
// per-reader ownership filtering and the per-query numeric pass.
//
// Contract:
//   - build_world(keys) validates exactly like the builder's structural
//     pass (duplicate physical keys, negative storage) and computes the
//     full run/untagged structure;
//   - append_keys(keys) adds records whose key indices are NEW (not
//     already present) and whose arrival preserves each run's tagged
//     order (the production append shape); throws otherwise;
//   - the world keeps its OWN copy of the key records, so later cell
//     mutations (publish/reclassify) do NOT leak in — the owner must
//     call set_key_meta after any in-place meta change, which updates
//     the copy and the uniformity probes in O(run size);
//   - build_query_layouts_multi_reader_world(...) consumes the world
//     and produces EXACTLY the same output as ..._multi_reader_bits on
//     the equivalent key table.
class llama_rerot_shared_world {
public:
    struct run {
        uint64_t episode_id = 0;
        llama_rerot_run_id run_id = LLAMA_REROT_RUN_INVALID;
        llama_rerot_node_id owner_node = LLAMA_REROT_NODE_INVALID;
        std::vector<uint32_t> rows;      // key indices, tagged order
        std::vector<llama_pos> storage;  // ascending (== tagged order)
        std::vector<uint32_t> d2t;       // d-position -> tagged index
        std::vector<uint32_t> t2d;       // tagged index -> d-position
        std::vector<int64_t> dev;        // d = storage - tagged idx, at d-positions
        bool contiguous = false;        // storage strictly +1 (dev constant)
        bool uniform = false;           // (visibility, frontier) shared by all rows
        llama_rerot_visibility u_vis = llama_rerot_visibility::normal;
        uint64_t u_frontier = 0;
        std::vector<uint32_t> fast_keys; // contiguous runs: key ids in d-order
    };

    llama_rerot_shared_world() = default;

    // Full structural pass over `keys` (same validation and same structure
    // as the builder's internal pass). Throws std::invalid_argument on
    // duplicate physical keys or negative storage positions.
    void build_world(const std::vector<llama_rerot_key_record> & keys);

    // Structural core over a CALLER-OWNED table: fills runs()/untagged_sorted()
    // (and the internal key map) without copying records. The one-shot bits
    // builder uses this to pay no record-copy; the world must not outlive
    // the caller's table and keys_ref() stays empty.
    void build_world_structure(const std::vector<llama_rerot_key_record> & keys);

    // Incremental append (production decode shape): every record must
    // carry a key index not yet present, and within each run the arrival
    // must preserve tagged order (storage, frontier then index ascending
    // at the tail). O(delta + runs) when the fast path holds; falls back
    // to a full rebuild when a run's tail order is violated.
    void append_keys(const std::vector<llama_rerot_key_record> & keys);

    // In-place meta update after publish/reclassify: refreshes the
    // record copy and the run's uniformity probe (O(rows of the run)).
    // `keys` must describe ONLY changed records (key index must exist).
    void set_key_meta(const std::vector<llama_rerot_key_record> & keys);

    // Production upsert (twelfth round, cache-level integration): like
    // append_keys, but a key index that ALREADY exists is REPLACED in place
    // (the ring-buffer recycle shape: apply_ubatch frees the victim cell and
    // immediately rewrites the same index). The old record leaves its run
    // bucket / untagged order; the new one enters (or stays) per its own
    // metadata. Interior order changes fall back to a tagged re-sort of the
    // touched run (never a world rebuild). Same validation as the other
    // incremental entries.
    void upsert_keys(const std::vector<llama_rerot_key_record> & keys);

    // O(1) tail-append fast path for the decode hot loop: the key index
    // must be NEW and its run contiguous+uniform with the arrival extending
    // the tail (storage +1, same (visibility, frontier)). Returns false
    // WITHOUT mutating when any precondition fails; the caller falls back
    // to upsert_keys.
    bool try_append_key_fast(const llama_rerot_key_record & key);

    // Remove records by key index (the apply_ubatch purge path: cells freed
    // by the position-overwrite purge are not part of the upsert set). The
    // records leave their run buckets / untagged order; `records` positions
    // stay stable (key_at marks them absent). Throws on an absent key.
    void remove_keys(const std::vector<uint32_t> & key_indices);

    size_t n_keys() const { return key_at.size(); }
    bool empty() const { return key_at.empty(); }
    // Access the record for key index k (k < n_keys()); the world's copy,
    // reflecting every accepted update.
    const llama_rerot_key_record & key(uint32_t k) const {
        return records[size_t(key_index_to_pos(k))];
    }

    // Records position of a live key index (throws std::out_of_range on an
    // absent/unknown index — callers on the tracked paths hold live keys).
    uint32_t pos_of(uint32_t k) const {
        if (k >= key_at.size() || key_at[k] == UINT32_MAX) {
            throw std::out_of_range("RERoT world: absent key index");
        }
        return key_at[k];
    }

    const std::vector<run> & runs() const { return runs_; }
    // Untagged key indices in (storage, key_index) order — the base arm.
    const std::vector<uint32_t> & untagged_sorted() const { return untagged_sorted_; }
    // The world's record store, position-indexed (key(k) == keys_ref()[pos
    // of k]); builders iterate this instead of a caller-owned table.
    const std::vector<llama_rerot_key_record> & keys_ref() const { return records; }

private:
    // key index -> position in `records` (or UINT32_MAX when absent).
    std::vector<uint32_t> key_at;
    std::vector<llama_rerot_key_record> records;
    // Structure-only builds borrow the caller's table; owned builds read
    // `records` (borrowed_table == nullptr).
    const std::vector<llama_rerot_key_record> * borrowed_table = nullptr;

    // The table the structural helpers (rebuild_run_structure,
    // recompute_uniform) must read rows from.
    const std::vector<llama_rerot_key_record> & structure_table() const {
        return borrowed_table ? *borrowed_table : records;
    }
    std::vector<run> runs_;
    std::vector<uint32_t> untagged_sorted_;

    uint32_t key_index_to_pos(uint32_t k) const { return key_at[k]; }

    void rebuild_run_structure(run & r);
    void recompute_uniform(run & r);
    void insert_untagged(uint32_t pos);
};

// World-consuming core: identical output to
// llama_rerot_build_query_layouts_multi_reader_bits given the world built
// from the same key table (same groups, entries, order,
// query_virtual_pos; same exceptions). The structural pass is skipped —
// the reader-side ownership filtering and per-query numeric pass run
// directly over the world's run/untagged structure.
// Direct-emission sink (fourteenth round): when passed to the world
// builder, the per-query merge writes straight into the FINAL layout
// arrays (group base and query index applied inline) — the intermediate
// per-query layouts and the assembly copy disappear. The sink arrays must
// be pre-sized to the exact totals; cursors track emission positions.
struct rerot_emission_sink {
    // Entries are written by raw cursor into a PRE-SIZED array (the sink
    // overwrites every element; a value-init pass would be pure waste).
    // Groups are APPENDED to a capacity-reserved vector (push_back) —
    // the group count is data-dependent and pre-sizing it by entry count
    // would both zero-fill megabytes and then be overwritten on the
    // closing resize growth.
    llama_rerot_attn_entry * entries = nullptr;
    std::vector<llama_rerot_attn_group> * groups_out = nullptr;
    // Optional span side-channel: bulk (const-effective contiguous)
    // segments append one span instead of COUNT entry writes. Non-null
    // => the builder AVOIDS the per-entry writes for those segments and
    // trusts the loader to expand them (layout.spans contracts the
    // invariant; validate() compares entry stream and span stream).
    // The cursor bookkeeping (entry_cursor) still advances by count.
    std::vector<llama_rerot_attn_layout::span> * spans_out = nullptr;
    std::vector<uint32_t> * query_offsets = nullptr;
    std::vector<llama_pos> * query_virtual_pos = nullptr;
    // Per-reader ubatch-row arrays: query_index_per_reader[r][qi] is the
    // ubatch row stamped on the groups emitted for that (reader, query).
    std::vector<const uint32_t *> query_index_per_reader;
    size_t entry_cursor = 0;
};

std::vector<std::vector<llama_rerot_query_layout>> llama_rerot_build_query_layouts_multi_reader_world(
    const std::vector<llama_rerot_reader_state> & readers,
    const std::vector<std::vector<llama_pos>> & query_storage_pos,
    const llama_rerot_shared_world & world,
    const std::vector<llama_rerot_owned_view> & base_owned_bits,
    std::vector<std::vector<llama_rerot_query_layout>> * output_scratch = nullptr,
    rerot_emission_sink * sink = nullptr);

// Pure logical document/tree model. It never stores physical KV indices.
class llama_rerot_document {
public:
    explicit llama_rerot_document(uint64_t episode_id = 1);

    void reset(uint64_t episode_id);

    uint64_t episode_id() const;
    llama_rerot_node_id root() const;

    llama_rerot_node_id create_child(
        llama_rerot_node_id parent,
        std::string title,
        llama_rerot_node_state state = llama_rerot_node_state::queued);

    llama_rerot_run_id append_run(
        llama_rerot_node_id owner,
        llama_rerot_visibility visibility,
        llama_pos storage_pos0,
        uint32_t token_count,
        uint64_t publish_epoch = 0,
        llama_rerot_segment_kind kind = llama_rerot_segment_kind::body);

    bool set_run_segment_kind(llama_rerot_run_id run_id, llama_rerot_segment_kind kind);

    bool set_run_token_count(llama_rerot_run_id run_id, uint32_t token_count);
    bool publish_run(llama_rerot_run_id run_id, uint64_t publish_epoch);
    bool reclassify_run(
        llama_rerot_run_id run_id,
        llama_rerot_visibility expected,
        llama_rerot_visibility replacement,
        uint64_t publish_epoch = 0);
    bool set_node_state(llama_rerot_node_id node_id, llama_rerot_node_state state);

    const llama_rerot_node * node(llama_rerot_node_id node_id) const;
    const llama_rerot_run * run(llama_rerot_run_id run_id) const;

    size_t node_count() const;
    size_t run_count() const;

    bool is_ancestor(llama_rerot_node_id ancestor, llama_rerot_node_id descendant) const;
    std::vector<uint32_t> tree_path(llama_rerot_node_id node_id) const;

    // DAG topology management (§§01, 03)
    bool is_dag_mode() const;
    void set_dag_mode(bool enabled);

    bool add_edge(llama_rerot_node_id before, llama_rerot_node_id after, std::string * error = nullptr);
    bool set_plan_rank(llama_rerot_node_id node_id, uint32_t rank);
    bool set_stage_role(llama_rerot_node_id node_id, llama_rerot_stage_role role);

    // Cycle-preferred topological sort (Kahn's algorithm with tie-break priority
    // defined in AGENTS.md §03.5):
    // For reader r, the cycle-preferred priority over plan_ranks is:
    //   rank > r in plan_order,
    //   rank < r in plan_order,
    //   r self last.
    // Returns nodes in order, or empty if a cycle exists or reader is invalid.
    std::vector<llama_rerot_node_id> topo_sort_cycle_preferred(
        const std::vector<llama_rerot_node_id> & candidates,
        llama_rerot_node_id reader,
        std::string * error = nullptr) const;

    // Render DAG view for reader:
    // Orders eligible started nodes via cycle-preferred topological sort,
    // ensuring predecessors precede successors, and reader's own work is last.
    // The synthesis reader (node 0) renders plan-rank order subject to
    // dependencies, independent of the started_nodes input order.
    // When frozen_read_publish_epoch != 0, every foreign PUBLIC run published
    // after that epoch is omitted — BODY and FRAME alike. Only the reader's
    // own runs (including its current FRAME) are exempt from the freeze.
    llama_rerot_reader_view build_dag_view(
        llama_rerot_node_id reader,
        const std::vector<llama_rerot_node_id> & started_nodes,
        uint64_t frozen_read_publish_epoch = 0) const;

    // Path-Anchored Cyclic DFS render of the whole tree for one reader: at
    // every node on the reader path the reader-branch child renders last and
    // preceding/following siblings keep document order; off-path subtrees
    // render in stable document order. The render depends only on tree
    // topology, run ownership/visibility, and token counts -- never on node
    // scheduling state (queued/running/retired) or queue order. Output runs
    // densely tile virtual positions [0, L) with each visible run exactly
    // once; query_virtual_pos == L. Throws std::out_of_range for an unknown
    // reader.
    llama_rerot_reader_view build_view(llama_rerot_node_id reader) const;
    // Reader-order providers (MM-R1 M06). `build_dag_view` and `build_view`
    // are the two orderings the runtime may select between; the provider is a
    // pure function of the document topology and the runs' visibility, never
    // of scheduling state (queued/running/retired) or physical slot order.
    //
    //   kahn        : cycle-preferred topological sort with the reader's own
    //                 work last -- the shipped DAG ordering.
    //   tree_dfs    : Path-Anchored Cyclic DFS -- at every node on the reader's
    //                 root path, the subtree containing the reader renders
    //                 LAST and the other subtrees keep document order.
    //
    // `order_version` guards order caches: bumping it invalidates every cached
    // order without touching the document, so a caller that changes provider
    // selection (or republishes structure) cannot reuse a stale order.
    enum class order_provider : uint8_t {
        kahn = 0,
        tree_dfs,
    };

    // Flattened LEAF order for one reader under a provider: the sequence of
    // leaf node ids the reader must be able to see, in view order. Returning
    // leaves (rather than runs) lets the caller compose the order with any
    // run-level visibility filter, and lets the order be cached per
    // (tree, reader, provider) because it depends on topology alone.
    // The reader's own leaf is always last when it is a leaf itself.
    // Throws std::out_of_range for an unknown reader.
    std::vector<llama_rerot_node_id> leaf_order(
            llama_rerot_node_id reader,
            order_provider provider) const;

    // Render the view for one reader under a provider. Equivalent to
    // build_dag_view(reader, started_nodes, epoch) for kahn and
    // build_view(reader) for tree_dfs -- the two selection paths share the
    // same run-level visibility rules, only the ORDER differs.
    llama_rerot_reader_view build_view_for(
            llama_rerot_node_id reader,
            order_provider provider,
            const std::vector<llama_rerot_node_id> & started_nodes = {},
            uint64_t frozen_read_publish_epoch = 0) const;

    // Monotonic order-version counter for this document. Bumped by
    // invalidate_order_cache(); order caches keyed on a stale value must be
    // rebuilt, so a caller can never reuse an order from before a structural
    // change.
    uint64_t order_version() const { return order_version_; }
    void invalidate_order_cache() { ++order_version_; }

    // Verifies episode/node/run id density and backlinks, the
    // publish-epoch/visibility contract, and -- for EVERY node as reader --
    // PAC-DFS density ([0, L), no overlap), exactly-once/completeness of
    // visible runs, view/source field fidelity, and sibling-block ordering
    // with own-subtree-last. Returns false and describes the first violated
    // invariant.
    bool validate(std::string * error = nullptr) const;

private:
    bool run_visible_to(const llama_rerot_run & run, llama_rerot_node_id reader) const;

    void render_node(
        llama_rerot_node_id node_id,
        llama_rerot_node_id reader,
        std::vector<llama_rerot_view_run> & out,
        llama_pos & virtual_pos) const;

    uint64_t episode_id_ = 0;
    bool is_dag_mode_ = false;
    uint64_t order_version_ = 1;
    std::vector<llama_rerot_node> nodes_;
    std::vector<llama_rerot_run> runs_;
};

// ---------------------------------------------------------------------------
// DDVR mathematical reference helpers
// ---------------------------------------------------------------------------

enum class llama_rerot_rope_layout : uint8_t {
    half = 0,
    interleaved,
};

struct llama_rerot_rope_config {
    uint32_t head_dim = 0;
    uint32_t rotary_dim = 0;
    double theta = 10000.0;
    double freq_scale = 1.0;
    llama_rerot_rope_layout layout = llama_rerot_rope_layout::half;

    // Number of rotary pairs assigned to each position axis. If all entries
    // are zero, all pairs use axis 0. For Qwen3.5 text IMRoPE, the first three
    // axes receive the text position and axis 3 remains zero.
    std::array<uint32_t, 4> axis_pair_count = { 0, 0, 0, 0 };
};

using llama_rerot_rope_pos = std::array<int64_t, 4>;

struct llama_rerot_ddvr_span {
    uint32_t key_begin = 0;
    uint32_t key_count = 0;
    int64_t storage_pos0 = 0;
    int64_t virtual_pos0 = 0;
};

llama_rerot_rope_pos llama_rerot_text_position(int64_t pos);

// Applies RoPE in place. Non-rotary tail dimensions are preserved.
bool llama_rerot_rope_apply(
    float * vector,
    size_t vector_size,
    const llama_rerot_rope_pos & position,
    const llama_rerot_rope_config & config,
    std::string * error = nullptr);

// Both functions consume unrotated query/key vectors. The materialized version
// rotates every key to its virtual position; the q-side version stores keys at
// writer-local positions and rotates one query per span. Both perform one
// global softmax over all visible keys.
std::vector<float> llama_rerot_ddvr_attention_materialized(
    const std::vector<float> & raw_query,
    const std::vector<float> & raw_keys,
    const std::vector<float> & values,
    uint32_t value_dim,
    int64_t query_virtual_pos,
    const std::vector<llama_rerot_ddvr_span> & spans,
    const llama_rerot_rope_config & config,
    float scale = 0.0f);

std::vector<float> llama_rerot_ddvr_attention_qside(
    const std::vector<float> & raw_query,
    const std::vector<float> & raw_keys,
    const std::vector<float> & values,
    uint32_t value_dim,
    int64_t query_virtual_pos,
    const std::vector<llama_rerot_ddvr_span> & spans,
    const llama_rerot_rope_config & config,
    float scale = 0.0f);

// ---------------------------------------------------------------------------
// FlashPrefill legal-fragment table helpers (CacheFragments; pure, no owner)
// ---------------------------------------------------------------------------
//
// Reusable per-view run tables for the FlashPrefill fragment path. The KV
// cache (cell owner) scans physical cells once per distinct reader view into
// member arrays, then splits each run ONCE via llama_rerot_split_table_
// fragments; per-query work afterwards touches fragments (F), never the full
// physical width (K). Visibility predicates mirror llama_rerot_build_query_
// layout exactly; any semantic change there must be mirrored here (the KV
// oracle test expands fragments back to per-query entries and compares).

struct llama_rerot_table_member {
    uint32_t key_index = 0; // physical K/V row
    llama_pos storage_pos = 0;
    uint64_t frontier = 0;
    llama_rerot_visibility visibility = llama_rerot_visibility::normal;
    // True when per-query ownership+causal gating still applies (private /
    // pending, own-node frontier-equal public, untagged base). False when the
    // member is visible to every query sharing the reader view (public with
    // older frontier, or strong-mode frontier-equal foreign node).
    bool gated = true;
};

struct llama_rerot_table_fragment {
    uint32_t begin = 0; // [begin, end) into the caller's member array
    uint32_t end = 0;
    llama_pos virtual_pos0 = 0; // first virtual position covered
    int64_t phase_bias = 0;     // storage_pos - virtual_pos, constant over [begin, end)
    llama_rerot_visibility visibility = llama_rerot_visibility::normal;
    bool gated = true;
};

// Split one run's members (sorted by storage, then frontier, then key) into
// fragments cut at virtual-BN edges, phase-bias changes, and visibility /
// gating changes. virtual_pos0 is the virtual position of members[0]; member
// i gets virtual_pos0 + i (members of one run occupy consecutive virtuals).
// Throws std::invalid_argument on block_k == 0 or member overflow.
std::vector<llama_rerot_table_fragment> llama_rerot_split_table_fragments(
    const llama_rerot_table_member * members,
    size_t n,
    llama_pos virtual_pos0,
    uint32_t block_k);

// Position/ownership-independent arm of the public_live visibility rule:
// visible to every query sharing the reader view, no causal check needed.
bool llama_rerot_cell_visible_public_full(
    const llama_kv_rerot_meta & meta,
    const llama_rerot_reader_state & reader);

// Owner-gated arm (private_control / pending_record, own-node frontier-equal
// public_live, untagged base): owner match plus owned-by-query plus causal
// bound. Mirrors the corresponding arms of llama_rerot_build_query_layout.
bool llama_rerot_cell_visible_gated(
    const llama_kv_rerot_meta & meta,
    const llama_rerot_reader_state & reader,
    bool is_untagged_base,
    bool owned_by_reader,
    llama_pos storage_pos,
    llama_pos query_storage_pos);

// --- R13-A compact span ABI (C05) -------------------------------------------------

// Version of the span wire/GPU layout. Bump when the 16-byte record changes
// meaning. Consumers that do not recognize this version must fall back to
// dense entries (spans are a compression, never the only authority).
static constexpr uint32_t LLAMA_REROT_SPAN_ABI_VERSION = 1;
static constexpr size_t   LLAMA_REROT_SPAN_ABI_SIZE   = 16; // 4 x u32

struct llama_rerot_span_coverage {
    uint64_t span_rows  = 0; // rows described by spans (sum of counts)
    uint64_t spill_rows = 0; // rows covered by authoritative entries only
    uint64_t total_rows = 0; // n_entries
    // True when the span table is empty (dense compatibility path) or when
    // every entry is span-covered.
    bool dense_only() const { return span_rows == 0; }
    bool full_coverage() const { return total_rows > 0 && spill_rows == 0; }
};

// Account span vs spill coverage WITHOUT expanding. O(n_spans) reads, no
// allocation. Assumes the layout passed validate(); on an invalid layout the
// returned accounting is unspecified (callers validate first).
llama_rerot_span_coverage llama_rerot_spans_coverage(
    const llama_rerot_attn_layout & layout);

// Expand the span table into a full dense entry stream, slot for slot, and
// return it. This is the CPU reference for the R13-A GPU expand kernel:
// the expanded stream MUST be bit-identical to layout.entries. Uncovered
// slots come from entries (dense compatibility); covered slots are the
// ascending key range tagged with the span's group_index. Throws
// std::runtime_error on span-table violations (zero count, overflow,
// non-monotone entry_index, range beyond n_entries).
std::vector<llama_rerot_attn_entry> llama_rerot_spans_expand(
    const llama_rerot_attn_layout & layout);


